name = "openq"
version = "0.1.0"
defaultTargets = ["OpenQ"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "Physlib"
git = "https://github.com/leanprover-community/physlib"
rev = "44c66d54be78db4693be9f8f92bd3b5ad124ed6f"

[[lean_lib]]
name = "OpenQ"
globs = ["OpenQ.+"]
