/-
Registration candidate, e002-i03. Derived from the unaccepted critic-written source
problems/amortization-collapse-for-superchannel-divergences-148275/work/critic/e002_i02/CriticSumsE2I02.lean.
Only import and namespace tokens are renamed. The historical source header below
is retained for provenance. This port is submitted for independent review.
-/

import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Analysis.Complex.Basic

/-!
Critic scratch (amortization problem, e002-i02). Generated by gen_sums.py.
Reordering lemmas for nested finite sums.
-/

namespace OpenQ.Problems.AmortizationCollapseSuperchannelDivergences_148275.StabilizedProofSums

theorem sum7_trace {α₀ α₁ α₂ α₃ α₄ α₅ α₆ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂] [Fintype α₃] [Fintype α₄] [Fintype α₅] [Fintype α₆]
    (F : α₀ → α₁ → α₂ → α₃ → α₄ → α₅ → α₆ → ℂ) :
    (∑ s, ∑ d, ∑ t, ∑ x, ∑ u, ∑ y, ∑ v, F s d t x u y v) =
      ∑ x, ∑ y, ∑ d, ∑ t, ∑ s, ∑ u, ∑ v, F s d t x u y v := by
  have hL : (∑ s, ∑ d, ∑ t, ∑ x, ∑ u, ∑ y, ∑ v, F s d t x u y v) =
      ∑ w : α₀ × α₁ × α₂ × α₃ × α₄ × α₅ × α₆, F w.1 w.2.1 w.2.2.1 w.2.2.2.1 w.2.2.2.2.1 w.2.2.2.2.2.1 w.2.2.2.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ x, ∑ y, ∑ d, ∑ t, ∑ s, ∑ u, ∑ v, F s d t x u y v) =
      ∑ v : α₃ × α₅ × α₁ × α₂ × α₀ × α₄ × α₆, F v.2.2.2.2.1 v.2.2.1 v.2.2.2.1 v.1 v.2.2.2.2.2.1 v.2.1 v.2.2.2.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.2.2.2.1, w.2.2.2.2.2.1, w.2.1, w.2.2.1, w.1, w.2.2.2.2.1, w.2.2.2.2.2.2)
      invFun := fun v => (v.2.2.2.2.1, v.2.2.1, v.2.2.2.1, v.1, v.2.2.2.2.2.1, v.2.1, v.2.2.2.2.2.2)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

theorem sum5_marg {α₀ α₁ α₂ α₃ α₄ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂] [Fintype α₃] [Fintype α₄]
    (F : α₀ → α₁ → α₂ → α₃ → α₄ → ℂ) :
    (∑ b, ∑ t, ∑ s, ∑ u, ∑ v, F b t s u v) =
      ∑ s, ∑ u, ∑ v, ∑ b, ∑ t, F b t s u v := by
  have hL : (∑ b, ∑ t, ∑ s, ∑ u, ∑ v, F b t s u v) =
      ∑ w : α₀ × α₁ × α₂ × α₃ × α₄, F w.1 w.2.1 w.2.2.1 w.2.2.2.1 w.2.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ s, ∑ u, ∑ v, ∑ b, ∑ t, F b t s u v) =
      ∑ v : α₂ × α₃ × α₄ × α₀ × α₁, F v.2.2.2.1 v.2.2.2.2 v.1 v.2.1 v.2.2.1 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.2.2.1, w.2.2.2.1, w.2.2.2.2, w.1, w.2.1)
      invFun := fun v => (v.2.2.2.1, v.2.2.2.2, v.1, v.2.1, v.2.2.1)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

theorem sum3_rot {α₀ α₁ α₂ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂]
    (F : α₀ → α₁ → α₂ → ℂ) :
    (∑ c, ∑ s, ∑ u, F c s u) =
      ∑ s, ∑ c, ∑ u, F c s u := by
  have hL : (∑ c, ∑ s, ∑ u, F c s u) =
      ∑ w : α₀ × α₁ × α₂, F w.1 w.2.1 w.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ s, ∑ c, ∑ u, F c s u) =
      ∑ v : α₁ × α₀ × α₂, F v.2.1 v.1 v.2.2 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.2.1, w.1, w.2.2)
      invFun := fun v => (v.2.1, v.1, v.2.2)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

theorem sum4_swap {α₀ α₁ α₂ α₃ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂] [Fintype α₃]
    (F : α₀ → α₁ → α₂ → α₃ → ℂ) :
    (∑ i, ∑ j, ∑ k, ∑ l, F i j k l) =
      ∑ i, ∑ k, ∑ j, ∑ l, F i j k l := by
  have hL : (∑ i, ∑ j, ∑ k, ∑ l, F i j k l) =
      ∑ w : α₀ × α₁ × α₂ × α₃, F w.1 w.2.1 w.2.2.1 w.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ i, ∑ k, ∑ j, ∑ l, F i j k l) =
      ∑ v : α₀ × α₂ × α₁ × α₃, F v.1 v.2.2.1 v.2.1 v.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.1, w.2.2.1, w.2.1, w.2.2.2)
      invFun := fun v => (v.1, v.2.2.1, v.2.1, v.2.2.2)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

theorem sum4_rev {α₀ α₁ α₂ α₃ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂] [Fintype α₃]
    (F : α₀ → α₁ → α₂ → α₃ → ℂ) :
    (∑ s, ∑ b, ∑ i, ∑ j, F s b i j) =
      ∑ i, ∑ j, ∑ b, ∑ s, F s b i j := by
  have hL : (∑ s, ∑ b, ∑ i, ∑ j, F s b i j) =
      ∑ w : α₀ × α₁ × α₂ × α₃, F w.1 w.2.1 w.2.2.1 w.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ i, ∑ j, ∑ b, ∑ s, F s b i j) =
      ∑ v : α₂ × α₃ × α₁ × α₀, F v.2.2.2 v.2.2.1 v.1 v.2.1 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.2.2.1, w.2.2.2, w.2.1, w.1)
      invFun := fun v => (v.2.2.2, v.2.2.1, v.1, v.2.1)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

theorem sum4_pairs {α₀ α₁ α₂ α₃ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂] [Fintype α₃]
    (F : α₀ → α₁ → α₂ → α₃ → ℂ) :
    (∑ b, ∑ t, ∑ x, ∑ y, F b t x y) =
      ∑ x, ∑ y, ∑ b, ∑ t, F b t x y := by
  have hL : (∑ b, ∑ t, ∑ x, ∑ y, F b t x y) =
      ∑ w : α₀ × α₁ × α₂ × α₃, F w.1 w.2.1 w.2.2.1 w.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ x, ∑ y, ∑ b, ∑ t, F b t x y) =
      ∑ v : α₂ × α₃ × α₀ × α₁, F v.2.2.1 v.2.2.2 v.1 v.2.1 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.2.2.1, w.2.2.2, w.1, w.2.1)
      invFun := fun v => (v.2.2.1, v.2.2.2, v.1, v.2.1)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

theorem sum5_rot {α₀ α₁ α₂ α₃ α₄ : Type} [Fintype α₀] [Fintype α₁] [Fintype α₂] [Fintype α₃] [Fintype α₄]
    (F : α₀ → α₁ → α₂ → α₃ → α₄ → ℂ) :
    (∑ d, ∑ t, ∑ s, ∑ u, ∑ v, F d t s u v) =
      ∑ t, ∑ s, ∑ u, ∑ v, ∑ d, F d t s u v := by
  have hL : (∑ d, ∑ t, ∑ s, ∑ u, ∑ v, F d t s u v) =
      ∑ w : α₀ × α₁ × α₂ × α₃ × α₄, F w.1 w.2.1 w.2.2.1 w.2.2.2.1 w.2.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have hR : (∑ t, ∑ s, ∑ u, ∑ v, ∑ d, F d t s u v) =
      ∑ v : α₁ × α₂ × α₃ × α₄ × α₀, F v.2.2.2.2 v.1 v.2.1 v.2.2.1 v.2.2.2.1 := by
    simp only [Fintype.sum_prod_type]
  rw [hL, hR]
  exact Fintype.sum_equiv
    { toFun := fun w => (w.2.1, w.2.2.1, w.2.2.2.1, w.2.2.2.2, w.1)
      invFun := fun v => (v.2.2.2.2, v.1, v.2.1, v.2.2.1, v.2.2.2.1)
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl } _ _ (fun _ => rfl)

end OpenQ.Problems.AmortizationCollapseSuperchannelDivergences_148275.StabilizedProofSums
